services:
  strapi:
    build: .
    container_name: strapi-app
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USER: strapi
      DATABASE_PASSWORD: strapi
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: key1,key2,key3,key4
      JWT_SECRET: superlongjwtsecret
      ADMIN_JWT_SECRET: superlongadminjwtsecret
      API_TOKEN_SALT: superlongapisalt
      TRANSFER_TOKEN_SALT: superlongtransfersalt
      ENCRYPTION_KEY: superlongencryptionkey
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: strapi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - strapi-db-data:/var/lib/mysql

volumes:
  strapi-db-data:
